name: gearbind
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py39heb7d2ae_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - biopython=1.79=py39h3811e60_1
  - boost=1.74.0=py39h5472131_5
  - boost-cpp=1.74.0=h312852a_4
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.16.0=h6cf1ce9_1008
  - cffi=1.15.0=py39h4bc2ebd_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - easydict=1.13=pyhff2d567_1
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonttools=4.33.3=py39hb9d737c_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.5.0=py39h9399b63_1
  - gdown=5.2.0=pyhd8ed1ab_1
  - gettext=0.19.8.1=h73d1719_1008
  - greenlet=1.1.2=py39h5a03fae_2
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=68.2=h9c3ff4c_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - kiwisolver=1.4.2=py39hf939315_1
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=31_he106b2a_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.68.4=h174f98d_1
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libopenblas=0.3.29=ha39b09d_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.17.0=h9b100fa_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.2=py39h700656a_0
  - multidict=6.6.3=py39h9399b63_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - olefile=0.47=pyhd8ed1ab_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre=8.45=h9c3ff4c_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h36c2ea0_0
  - propcache=0.3.1=py39h9399b63_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycairo=1.21.0=py39h0934665_1
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pytorch_geometric=2.6.1=pyhecae5ae_2
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - rdkit=2022.03.2=py39h89e00b9_0
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.68=py39he59360d_1
  - setuptools=78.1.1=py39h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - soupsieve=2.7=pyhd8ed1ab_0
  - sqlalchemy=1.4.36=py39hb9d737c_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.1=py39h9399b63_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - decorator==5.2.1
      - dm-tree==0.1.8
      - fair-esm==2.0.0
      - filelock==3.13.1
      - fsspec==2024.6.1
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.4
      - jinja2==3.1.4
      - joblib==1.5.2
      - lmdb==1.6.2
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - numpy==1.23.5
      - pandas==1.5.3
      - pillow==11.0.0
      - rdkit-pypi==2022.9.5
      - regex==2025.11.3
      - requests==2.28.1
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tokenizers==0.15.2
      - torch==2.1.0+cu121
      - torch-cluster==1.6.3+pt21cu121
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torchaudio==2.1.0+cu121
      - torchdrug==0.2.1
      - torchvision==0.16.0+cu121
      - transformers==4.37.0
      - triton==2.1.0
      - typing-extensions==4.12.2
      - urllib3==1.26.13
prefix: /home/chengwang/miniconda3/envs/gearbind
